#!/usr/bin/env node
// Front-end build: `npm run build`
//
//  1. src/dashboard/*.js   → public/js/dashboard.js   (concatenated in filename
//     order into ONE classic script, so functions/variables stay shared exactly
//     as when the code lived inline in dashboard.html)
//  2. src/patek-desk/app.jsx → public/js/patek-desk.js (esbuild: JSX compiled,
//     React bundled — no runtime Babel or CDN imports)
//  3. Tailwind               → public/css/app.css      (replaces the Tailwind CDN)
//  4. Cache-busting: rewrites ?v=<hash> on those assets (and style.css) in the
//     HTML pages so browsers pick up new builds immediately.
//
// The outputs are committed, so the server needs no build step to run.

'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const r = (...p) => path.join(ROOT, ...p);
const watch = process.argv.includes('--watch');

function buildDashboard() {
  const dir = r('src/dashboard');
  const files = fs.readdirSync(dir).filter(f => f.endsWith('.js')).sort();
  // Deliberately NOT strict mode: the code was written as a sloppy-mode inline script.
  const out = ['// GENERATED by scripts/build.js from src/dashboard/*.js — edit those files, not this one.'];
  for (const f of files) out.push(`\n// ═══ ${f} ═══\n` + fs.readFileSync(path.join(dir, f), 'utf8'));
  const js = out.join('\n');
  // Fail the build on a syntax error rather than shipping a broken page
  try { new Function(js); } catch (e) { throw new Error(`dashboard.js syntax error: ${e.message}`); }
  fs.mkdirSync(r('public/js'), { recursive: true });
  fs.writeFileSync(r('public/js/dashboard.js'), js);
  console.log(`  dashboard.js   ${files.length} parts, ${(js.length / 1024).toFixed(0)} KB`);
}

function buildPatekDesk() {
  require('esbuild').buildSync({
    entryPoints: [r('src/patek-desk/app.jsx')],
    outfile: r('public/js/patek-desk.js'),
    bundle: true,
    minify: true,
    format: 'iife',
    target: ['es2020'],
    jsx: 'transform',
    define: { 'process.env.NODE_ENV': '"production"' },
    legalComments: 'none',
    logLevel: 'warning',
  });
  console.log(`  patek-desk.js  ${(fs.statSync(r('public/js/patek-desk.js')).size / 1024).toFixed(0)} KB`);
}

function buildCss() {
  const cli = require.resolve('tailwindcss/lib/cli.js');
  execFileSync(process.execPath, [cli, '-c', r('tailwind.config.js'), '-i', r('src/styles/tailwind.css'), '-o', r('public/css/app.css'), '--minify'], { stdio: ['ignore', 'ignore', 'pipe'] });
  console.log(`  app.css        ${(fs.statSync(r('public/css/app.css')).size / 1024).toFixed(0)} KB`);
}

function bustCaches() {
  const assets = ['js/dashboard.js', 'js/patek-desk.js', 'css/app.css', 'style.css', 'neon.css', 'cursor.js'];
  const hash = {};
  for (const a of assets) hash[a] = crypto.createHash('sha1').update(fs.readFileSync(r('public', a))).digest('hex').slice(0, 10);
  for (const page of fs.readdirSync(r('public')).filter(f => f.endsWith('.html'))) {
    const p = r('public', page);
    const before = fs.readFileSync(p, 'utf8');
    let after = before;
    for (const a of assets) {
      const re = new RegExp(`((?:src|href)=")(/?)${a.replace(/[.]/g, '\\.')}(?:\\?v=[0-9a-f]+)?"`, 'g');
      after = after.replace(re, `$1$2${a}?v=${hash[a]}"`);
    }
    if (after !== before) fs.writeFileSync(p, after);
  }
}

function buildAll() {
  const t = Date.now();
  buildDashboard();
  buildPatekDesk();
  buildCss();
  bustCaches();
  console.log(`built in ${Date.now() - t} ms`);
}

buildAll();

if (watch) {
  console.log('watching src/, tailwind.config.js, public/style.css and public/neon.css …');
  let timer;
  const rebuild = () => { clearTimeout(timer); timer = setTimeout(() => { try { buildAll(); } catch (e) { console.error(e.message); } }, 150); };
  fs.watch(r('src'), { recursive: true }, rebuild);
  fs.watch(r('tailwind.config.js'), rebuild);
  fs.watch(r('public/style.css'), rebuild);
  fs.watch(r('public/neon.css'), rebuild);
}
